"""payout attempt counter

Revision ID: 0f3f87ab65c6
Revises: b38d3a578ff3
Create Date: 2026-08-12 15:43:43.759382

"""
from alembic import op
import sqlalchemy as sa


revision = '0f3f87ab65c6'
down_revision = 'b38d3a578ff3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payout_attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payout_attempts')
    # ### end Alembic commands ###
