"""provider call journal

The durable record of every money-moving request made to the payment provider.
See app/modules/payments/journal.py for what it is for.

Purely additive: one new table, no change to any existing one, so it applies to
a live database without touching a row that money depends on.

Revision ID: 16614ae8f886
Revises: 0f3f87ab65c6
Create Date: 2026-08-13 21:30:32.644199

"""
from alembic import op
import sqlalchemy as sa


revision = '16614ae8f886'
down_revision = '0f3f87ab65c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='providercallstatus'), nullable=False),
    sa.Column('provider_ref', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_provider_calls_payment_id'), 'provider_calls', ['payment_id'], unique=False)
    op.create_index(op.f('ix_provider_calls_status'), 'provider_calls', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_calls_status'), table_name='provider_calls')
    op.drop_index(op.f('ix_provider_calls_payment_id'), table_name='provider_calls')
    op.drop_table('provider_calls')
    # ### end Alembic commands ###
    # Postgres leaves the enum type behind when the table goes, and the next
    # upgrade then fails with "type providercallstatus already exists". SQLite
    # has no such type, where checkfirst makes this a no-op.
    sa.Enum(name='providercallstatus').drop(op.get_bind(), checkfirst=True)
