"""job photos

Revision ID: 561f3111c1b8
Revises: ae5818643616
Create Date: 2026-08-07 10:42:45.663715

"""
from alembic import op
import sqlalchemy as sa


revision = '561f3111c1b8'
down_revision = 'ae5818643616'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_photos_job_id'), 'job_photos', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_photos_job_id'), table_name='job_photos')
    op.drop_table('job_photos')
    # ### end Alembic commands ###
