"""disputes

Revision ID: 8aa48747785e
Revises: 19344dedbab3
Create Date: 2026-08-11 02:21:05.201995

"""
from alembic import op
import sqlalchemy as sa


revision = '8aa48747785e'
down_revision = '19344dedbab3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
