"""disputes table missed by empty migration

Revision ID: b38d3a578ff3
Revises: 83996a83d343
Create Date: 2026-08-12 12:14:51.928832

"""
from alembic import op
import sqlalchemy as sa


revision = 'b38d3a578ff3'
down_revision = '83996a83d343'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('opened_by', sa.Integer(), nullable=False),
    sa.Column('against_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('WORK_NOT_DONE', 'QUALITY', 'DAMAGE', 'NO_SHOW', 'OVERCHARGED', 'UNSAFE', 'OTHER', name='disputereason'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='disputestatus'), nullable=False),
    sa.Column('previous_job_status', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.Enum('DISMISSED', 'PARTIAL_REFUND', 'FULL_REFUND', name='disputeoutcome'), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('refunded_cents', sa.Integer(), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['against_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_job_id'), 'disputes', ['job_id'], unique=False)
    op.create_index(op.f('ix_disputes_opened_by'), 'disputes', ['opened_by'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_opened_by'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_job_id'), table_name='disputes')
    op.drop_table('disputes')
    # ### end Alembic commands ###
