import * as AppleAuthentication from "expo-apple-authentication";
import * as AuthSession from "expo-auth-session";
import * as Crypto from "expo-crypto";
import * as WebBrowser from "expo-web-browser";
import { Platform } from "react-native";
import { SOCIAL_CLIENT_IDS } from "../config";

WebBrowser.maybeCompleteAuthSession();

export type SocialProvider = "google" | "apple" | "microsoft";

export const PROVIDER_LABEL: Record<SocialProvider, string> = {
  google: "Google",
  apple: "Apple",
  microsoft: "Microsoft",
};

const DISCOVERY: Record<"google" | "microsoft", AuthSession.DiscoveryDocument> = {
  google: {
    authorizationEndpoint: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenEndpoint: "https://oauth2.googleapis.com/token",
  },
  microsoft: {
    authorizationEndpoint:
      "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    tokenEndpoint: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
  },
};

export class SocialCancelled extends Error {}

/**
 * Run the provider's sign-in and return its ID token.
 *
 * The **implicit** flow is used deliberately: we only need a signed ID token for
 * the backend to verify, and a code exchange would require a client secret that
 * cannot be shipped inside an app. Nonce is generated by AuthSession and checked
 * by the provider; the backend independently verifies signature, issuer,
 * audience, and expiry.
 */
export async function signInWithProvider(provider: SocialProvider): Promise<string> {
  if (provider === "apple") return signInWithApple();

  const clientId = SOCIAL_CLIENT_IDS[provider];
  if (!clientId) throw new Error(`${PROVIDER_LABEL[provider]} sign-in is not configured`);

  const redirectUri = AuthSession.makeRedirectUri();
  const request = new AuthSession.AuthRequest({
    clientId,
    redirectUri,
    scopes: ["openid", "email", "profile"],
    responseType: AuthSession.ResponseType.IdToken,
    extraParams: { nonce: Crypto.randomUUID() },
  });

  const result = await request.promptAsync(DISCOVERY[provider]);
  if (result.type === "cancel" || result.type === "dismiss") throw new SocialCancelled();
  if (result.type !== "success") {
    throw new Error(result.type === "error" ? result.error?.message ?? "Sign-in failed" : "Sign-in failed");
  }
  const idToken = result.params?.id_token;
  if (!idToken) throw new Error(`${PROVIDER_LABEL[provider]} did not return an identity token`);
  return idToken;
}

async function signInWithApple(): Promise<string> {
  if (Platform.OS !== "ios") {
    // Sign in with Apple on the web needs a separate JS SDK and its own service
    // ID; keeping it iOS-only avoids shipping a button that dead-ends.
    throw new Error("Apple sign-in is available on iOS");
  }
  try {
    const credential = await AppleAuthentication.signInAsync({
      requestedScopes: [
        AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
        AppleAuthentication.AppleAuthenticationScope.EMAIL,
      ],
    });
    if (!credential.identityToken) throw new Error("Apple did not return an identity token");
    return credential.identityToken;
  } catch (e) {
    if ((e as { code?: string }).code === "ERR_REQUEST_CANCELED") throw new SocialCancelled();
    throw e;
  }
}
